import { balanceBraces } from './balancer.js';

// Module-level blocklist — shared by the early nuclear removal pass and Phase 2.
const BANNED_IMPORTS = ['spring', 'SpringConfig', 'measureSpring'];

/**
 * TSX Code Validator & Fixer for Remotion Animations
 *
 * Validates and auto-fixes TSX code generated by LLMs to ensure:
 * - Correct imports and component structure
 * - Content is centered and visible
 * - No black screens from Sequence misuse
 * - Typography is clean and professional
 * - Animations use proper Remotion APIs
 * - Layout fills the viewport correctly
 * - Safe area margins are enforced
 */

/**
 * Safely extracts and replaces style={{ ... }} content for a given JSX tag.
 * Unlike regex with [\s\S]*?, this properly counts brace nesting so it
 * won't be fooled by template literals like `${val}}` or nested objects.
 *
 * @param {string} code - Full TSX source
 * @param {string} tag - Tag name to match (e.g., 'div', 'AbsoluteFill')
 * @param {function} transformer - Called with style content string; return new content or null to skip
 * @returns {string} - Modified code
 */
function safeStyleReplace(code, tag, transformer) {
    const pattern = new RegExp(`<${tag}\\s+style=\\{\\{`, 'g');
    let result = '';
    let lastIndex = 0;
    let match;

    while ((match = pattern.exec(code)) !== null) {
        const styleStart = match.index + match[0].length;
        // Count braces to find the matching }}
        let depth = 2; // We already consumed {{
        let i = styleStart;
        let inString = null;

        while (i < code.length && depth > 0) {
            const ch = code[i];

            // Handle strings
            if (!inString && (ch === "'" || ch === '"' || ch === '`')) {
                inString = ch;
                i++;
                continue;
            }
            if (inString) {
                if (ch === '\\') { i += 2; continue; }
                if (ch === inString) {
                    if (inString === '`' || ch !== '`') inString = null;
                }
                if (inString === '`' && ch === '$' && code[i + 1] === '{') {
                    // Template interpolation — skip to matching }
                    let tDepth = 1;
                    i += 2;
                    while (i < code.length && tDepth > 0) {
                        if (code[i] === '{') tDepth++;
                        else if (code[i] === '}') tDepth--;
                        i++;
                    }
                    continue;
                }
                i++;
                continue;
            }

            if (ch === '{') depth++;
            else if (ch === '}') depth--;
            if (depth > 0) i++;
            else break; // depth hit 0, i points at first } of }}
        }

        if (depth === 0) {
            const styleContent = code.slice(styleStart, i - 1); // -1 because i is at first } of }}
            const newContent = transformer(styleContent);
            if (newContent !== null && newContent !== undefined) {
                result += code.slice(lastIndex, styleStart) + newContent + '}}';
                lastIndex = i + 1; // +1 to skip the second }
                // Adjust regex lastIndex
                pattern.lastIndex = lastIndex;
                continue;
            }
        }

        // No change — just continue
        result += code.slice(lastIndex, match.index + match[0].length);
        lastIndex = match.index + match[0].length;
    }

    result += code.slice(lastIndex);
    return result;
}

/**
 * Full validation + fix pipeline. Returns { code, fixes[], warnings[] }
 */
export async function validateAndFix(code, settings = {}) {
    const fixes = [];
    const warnings = [];
    let fixed = code;

    // ======== PHASE 0 (PRE): NUCLEAR SPRING REMOVAL ========
    // Must run before all other phases so banned symbols never reach the bundler.
    BANNED_IMPORTS.forEach(banned => {
        // Remove from remotion import statements
        fixed = fixed.replace(new RegExp(`,?\\s*\\b${banned}\\b`, 'g'), '');
        // Replace simple spring() call declarations with a safe interpolate fallback
        fixed = fixed.replace(
            /const\s+(\w+)\s*=\s*spring\s*\([^)]*\)/g,
            `const $1 = interpolate(frame, [0, 25], [0, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })`
        );
    });

    // ======== PHASE 0: STRIP TRAILING NON-CODE GARBAGE ========
    // LLMs sometimes append random text, Chinese characters, etc. after the last closing brace
    fixed = stripTrailingGarbage(fixed, fixes);

    // ======== PHASE 1: SYNTAX CLEANUP ========

    // Strip markdown code fences if LLM included them
    if (fixed.includes('```')) {
        fixed = fixed.replace(/```tsx?\s*\n?/g, '').replace(/```\s*\n?/g, '').trim();
        fixes.push('Stripped markdown code fences');
    }

    // New: Strip registerRoot() calls and imports as they are handled by the server wrapper
    if (fixed.includes('registerRoot')) {
        const originalLength = fixed.length;
        // Remove individual calls: registerRoot(Anything);
        fixed = fixed.replace(/registerRoot\s*\([^)]*\);?/g, '');
        // Remove from imports: { ..., registerRoot, ... }
        fixed = fixed.replace(/registerRoot,?\s*/g, '');
        fixed = fixed.replace(/,\s*registerRoot/g, '');

        if (fixed.length < originalLength) {
            fixes.push('Stripped registerRoot() calls and imports (handled by server)');
        }
    }

    // New: Strip LLM artifacts like <ctrl63>
    const junkPattern = /<ctrl\d+>/gi;
    if (junkPattern.test(fixed)) {
        const originalLength = fixed.length;
        fixed = fixed.replace(junkPattern, '').trim();
        if (fixed.length < originalLength) {
            fixes.push('Stripped LLM artifacts (<ctrl...>)');
        }
    }

    // ======== PHASE 1.3: TEMPLATE LITERAL FIX ========
    // CRITICAL: Must run BEFORE string literal fix and brace balancing.
    // Gemini's #1 syntax error source: broken template literals with extra braces,
    // garbage in interpolations, or mangled ternary expressions.
    fixed = fixTemplateLiterals(fixed, fixes);

    // ======== PHASE 1.4: STROKEDASHARRAY SPACE FIX ========
    // Problem: strokeDasharray={`12 8`} crashes esbuild because space-separated 
    // numbers in template literals inside JSX are misread as regex operators.
    if (fixed.includes('strokeDasharray={')) {
        const originalLength = fixed.length;
        fixed = fixed.replace(/strokeDasharray=\{\s*[`'"]([^`'"]+)[`'"]\s*\}/g, 'strokeDasharray="$1"');
        if (fixed.length !== originalLength) {
            fixes.push('Converted template literal strokeDasharray to string literal (esbuild regex crash fix)');
        }
    }

    // ======== PHASE 1.4b: STROKEDASHARRAY ATTRIBUTE NORMALIZER ========
    // Second pass: catches any remaining JSX expression forms the first pass missed,
    // e.g. strokeDasharray={`12 8`} where whitespace patterns differ.
    fixed = fixed.replace(
        /strokeDasharray=\{[`'"]([^`'"]+)[`'"]\}/g,
        'strokeDasharray="$1"'
    );

    // ======== PHASE 1.5: STRING LITERAL FIX ========
    fixed = fixUnterminatedStrings(fixed, fixes);

    // ======== PHASE 1.6: JSX TAG FIX ========
    fixed = fixUnclosedTags(fixed, fixes);

    // ======== PHASE 2: IMPORT VALIDATION ========
    fixed = fixImports(fixed, fixes);

    // ======== PHASE 3: COMPONENT STRUCTURE ========
    fixed = fixComponentStructure(fixed, fixes, warnings);

    // ======== PHASE 4: REMOTION API FIXES ========
    fixed = fixRemotionAPIs(fixed, fixes);

    // ======== PHASE 5: VISUAL / LAYOUT FIXES ========
    fixed = fixLayout(fixed, fixes, settings, warnings);

    // ======== PHASE 5.1: BACKGROUND SHORTHAND FIX ========
    // Problem 3: background: 'linear-gradient(...)' silently breaks in Remotion.
    // Must split into backgroundImage: + backgroundColor: (or just backgroundImage: for text clips).
    fixed = fixBackgroundShorthand(fixed, fixes);

    // ======== PHASE 5.1b: BACKGROUND SHORTHAND SWEEP (ALL ELEMENTS) ========
    // fixBackgroundShorthand handles style objects with complex patterns; this pass
    // catches any remaining `background: 'gradient(...)'` the function-based pass missed.
    fixed = fixed.replace(
        /\bbackground:\s*(['"`])(linear-gradient|radial-gradient|conic-gradient)/g,
        'backgroundImage: $1$2'
    );

    // ======== PHASE 5.2: SPRING() BAN — REPLACE WITH INTERPOLATE() ========
    // Problem 4/5: spring() crashes with "Frame NaN is not finite" in this pipeline.
    // Replace every spring() call with an equivalent interpolate() + Math.min/max clamp.
    fixed = replaceSpringWithInterpolate(fixed, fixes);

    // ======== PHASE 5.2b: INTERPOLATE() CLAMP INJECTION ========
    // Problem: interpolate() without extrapolateLeft/Right: 'clamp' can produce NaN or Infinity
    // on the last frame (when frame === durationInFrames), crashing the WebGL context mid-render.
    // This is a primary cause of the "Target closed" renderer crash at 80-100% progress.
    // Fix: Inject both clamp options into every interpolate() call that is missing them.
    fixed = clampInterpolates(fixed, fixes);

    // ======== PHASE 5.3: RIGHT/BOTTOM → LEFT/TOP POSITIONING FIX ========
    // Problem 7/13: right: and bottom: can behave unexpectedly.
    // Convert to left:/top: with explicit pixel values where width/height are known.
    fixed = fixRightBottomPositioning(fixed, fixes, settings);

    // ======== PHASE 5.4: STRING SAFETY ========
    // Problem 14: Degree symbol ° breaks esbuild parser.
    fixed = fixStringSafety(fixed, fixes);

    // ======== PHASE 5.5: WHITESPACE & OVERFLOW ========
    // Problem 12: Text elements need whiteSpace: 'nowrap'; containers need overflow: 'hidden'.
    fixed = fixWhitespaceOverflow(fixed, fixes);

    // ======== PHASE 5.6: SVG OVERLAY SANITIZER ========
    // Complex SVG animated scenes: ensure overflow="visible" so animated strokes aren't clipped,
    // and that SVG overlays have correct HTML attributes for proper viewport sizing.
    fixed = fixSVGOverlays(fixed, fixes);

    // ======== PHASE 5.7: ENFORCE position:'absolute' ON POSITIONED CHILDREN ========
    // Root cause of most blank scenes: child divs that use top:/left: pixel coordinates
    // but are missing position:'absolute' — they render outside the viewport or at 0,0
    // and collapse to 0px, making the scene appear blank even when colors are correct.
    fixed = fixed.replace(
        /style=\{\{([^}]*)\b(top|left)\s*:\s*\d+([^}]*)\}\}/g,
        (match, before, prop, after) => {
            if (match.includes('position:')) return match;
            const inner = before + prop + ':' + after;
            return `style={{ position: 'absolute', ${inner} }}`;
        }
    );

    // ======== PHASE 5.8: WARN ON ABSOLUTE DIVS MISSING EXPLICIT HEIGHT ========
    // Absolute-positioned containers without a height declaration collapse to 0px,
    // making their content invisible. Cannot auto-fix without knowing content size,
    // but surface it as a warning so the retry loop can flag it to the LLM.
    {
        const absoluteDivCount =
            (fixed.match(/position:\s*['"]absolute['"]/g) || []).length;
        const heightDeclCount =
            (fixed.match(/\bheight\s*:\s*\d+/g) || []).length;

        if (absoluteDivCount > heightDeclCount + 2) {
            warnings.push(
                `${absoluteDivCount - heightDeclCount} absolute div(s) may be missing explicit height — ` +
                `containers without height collapse to 0px`
            );
        }
    }

    // ======== PHASE 6: TYPOGRAPHY & STYLING ========
    fixed = fixTypography(fixed, fixes, settings, warnings);

    // ======== PHASE 7: ANIMATION QUALITY ========
    fixed = fixAnimations(fixed, fixes, warnings);

    // ======== PHASE 8: SEQUENCE SAFETY ========
    fixed = fixSequenceSafety(fixed, fixes, warnings);

    // ======== PHASE 8.1: ROOT OVERFLOW GUARD ========
    // Root 1920×1080 container MUST have overflow:'hidden' to clip out-of-frame elements.
    fixed = enforceRootOverflowHidden(fixed, fixes);

    // ======== PHASE 8.2: FONT SIZE CLAMP (12–144px) ========
    // Fonts outside this range are either unreadable or overflow their containers.
    fixed = clampFontSizes(fixed, fixes, warnings);

    // ======== PHASE 8.3: TEXT CONTAINER WIDTH GUARD ========
    // Text containers without explicit width/maxWidth can stretch off-screen when
    // content is longer than expected (especially with placeholders replaced at fill time).
    fixed = guardTextContainerWidths(fixed, fixes, warnings);

    // ======== PHASE 8.4: CSS ANIMATION REMOVAL ========
    // CSS animation: and transition: properties don't work in Remotion's renderer.
    // Replace them with static equivalents so elements at least appear.
    fixed = removeCSSAnimations(fixed, fixes);

    // ======== PHASE 8.5: SAFE ZONE ENFORCEMENT ========
    // Absolute-positioned elements within 40px of any edge may be clipped on some displays.
    // Warn (don't auto-fix — layout intent is unknown) when edge values are too tight.
    fixed = warnSafeZoneViolations(fixed, warnings);

    // ======== PHASE 9: FINAL SYNTAX BALANCING ========
    // CRITICAL: Must be last to catch any structural errors introduced by previous phases
    const originalPreBalance = fixed;
    fixed = balanceBraces(fixed);
    if (fixed !== originalPreBalance) {
        fixes.push('Balanced unclosed braces/brackets (final syntax safeguard)');
    }

    // ======== PHASE 10: FAST SYNTAX VERIFICATION ========
    // Use esbuild's transform to quickly check if the code parses.
    // If it fails, attempt targeted fixes for the specific error type.
    try {
        // Dynamic import to avoid breaking if esbuild isn't available
        const esbuild = await import('esbuild');
        try {
            await esbuild.transform(fixed, { loader: 'tsx', logLevel: 'silent' });
        } catch (parseError) {
            const errMsg = parseError.message || '';
            const lineMatch = errMsg.match(/:(\d+):(\d+)/);
            if (lineMatch) {
                const errLine = parseInt(lineMatch[1]) - 1;
                const errCol  = parseInt(lineMatch[2]) - 1;
                const lines = fixed.split('\n');
                if (errLine >= 0 && errLine < lines.length) {
                    const badLine = lines[errLine];
                    let cleaned = badLine;

                    if (errMsg.includes('Unterminated regular expression')) {
                        // Gemini generated a regex literal (/pattern/) where the closing /
                        // is missing or the regex spans a line (raw newline in regex).
                        // Strategy: find the opening / at errCol, scan forward to end of line,
                        // and close the regex there. This produces valid (if imperfect) syntax.
                        const slash = errCol >= 0 ? errCol : cleaned.indexOf('/', 0);
                        if (slash >= 0 && cleaned[slash] === '/') {
                            let j = slash + 1;
                            let inClass = false;
                            while (j < cleaned.length) {
                                const c = cleaned[j];
                                if (c === '\\') { j += 2; continue; }
                                if (!inClass && c === '[') { inClass = true; }
                                else if (inClass && c === ']') { inClass = false; }
                                else if (!inClass && c === '/') { break; } // already closed
                                j++;
                            }
                            if (j >= cleaned.length) {
                                // Regex wasn't closed — close it + optional flags
                                if (inClass) cleaned += ']';  // close open character class too
                                cleaned += '/';
                            }
                        }
                    } else {
                        // Default: clean all template literals on the error line
                        // (using proper stack-based depth counter — same fix as Pattern 5)
                        cleaned = cleaned.replace(/`([^`]*)`/g, (m, content) => {
                            const stack = [];
                            let out = '';
                            for (let i = 0; i < content.length; i++) {
                                if (content[i] === '$' && content[i + 1] === '{') {
                                    stack.push('$'); out += '${'; i++; continue;
                                }
                                if (content[i] === '{' && stack.length > 0) {
                                    stack.push('{'); out += '{'; continue;
                                }
                                if (content[i] === '}' && stack.length > 0) {
                                    stack.pop(); out += '}'; continue;
                                }
                                if (content[i] === '}' && stack.length === 0) continue; // extra }
                                out += content[i];
                            }
                            return '`' + out + '`';
                        });
                        // Also fix }}> ternary pattern outside backticks
                        cleaned = cleaned.replace(/(\w+)\s*\}{2,}>\s*(\d)/g, '$1 > $2');
                        // Also strip injected CSS property fragments
                        cleaned = cleaned.replace(/,\s*\w+:\s*'[^']*'/g, '');
                    }

                    if (cleaned !== badLine) {
                        lines[errLine] = cleaned;
                        fixed = lines.join('\n');
                        fixes.push(`Phase 10: Aggressive syntax fix on line ${errLine + 1}`);
                    }
                }
            }
        }
    } catch (e) {
        // esbuild not available — skip verification (non-critical)
    }

    if (fixes.length > 0) {
        console.log(`🔧 TSX Validator applied ${fixes.length} fix(es):`);
        fixes.forEach(f => console.log(`   ✅ ${f}`));
    }
    if (warnings.length > 0) {
        console.log(`⚠️ TSX Validator warnings:`);
        warnings.forEach(w => console.log(`   ⚠️ ${w}`));
    }

    return { code: fixed, fixes, warnings };
}

// ====================================================================
// PHASE 2: IMPORT VALIDATION
// ====================================================================

function fixImports(code, fixes) {
    let fixed = code;

    // Fix misplaced React hooks/items in Remotion imports (most common cause of 500 errors)
    const reactHooks = ['useState', 'useEffect', 'useMemo', 'useCallback', 'useRef', 'useLayoutEffect', 'useContext', 'useReducer', 'Fragment'];

    // 1. Detect hooks inside 'remotion' import brackets
    const remotionMatch = fixed.match(/import\s*\{([^}]+)\}\s*from\s*['"]remotion['"]/);
    if (remotionMatch) {
        const existingRemotionImports = remotionMatch[1];
        const remotionImports = existingRemotionImports.split(',').map(s => s.trim()).filter(Boolean);
        const hooksToMove = remotionImports.filter(imp => reactHooks.includes(imp));

        if (hooksToMove.length > 0) {
            fixes.push(`Redirected React hook(s) from Remotion to React: ${hooksToMove.join(', ')}`);

            // Remove hooks from Remotion import
            const cleanedRemotion = remotionImports.filter(imp => !reactHooks.includes(imp));
            fixed = fixed.replace(
                /import\s*\{[^}]+\}\s*from\s*['"]remotion['"]/,
                `import { ${cleanedRemotion.join(', ')} } from 'remotion'`
            );

            // Add hooks to React import
            const reactSpecifierMatch = fixed.match(/import\s*(?:React\s*,?\s*)?\{?([^}]*)\}?\s*from\s*['"]react['"]/);
            if (reactSpecifierMatch) {
                const reactNamedImports = reactSpecifierMatch[1];
                let newReactImport;
                if (!reactNamedImports || reactNamedImports.trim() === '') {
                    // Was "import React from 'react'" or similar
                    newReactImport = `import React, { ${hooksToMove.join(', ')} } from 'react'`;
                } else {
                    // Already has named imports
                    const existingReactNames = reactNamedImports.split(',').map(s => s.trim()).filter(Boolean);
                    const filteredHooks = hooksToMove.filter(h => !existingReactNames.includes(h));
                    if (filteredHooks.length > 0) {
                        const combined = [...existingReactNames, ...filteredHooks];
                        newReactImport = `import React, { ${combined.join(', ')} } from 'react'`;
                    }
                }
                if (newReactImport) {
                    fixed = fixed.replace(/import\s*(?:React\s*,?\s*)?\{?([^}]*)\}?\s*from\s*['"]react['"]/, newReactImport);
                }
            } else {
                // No React import at all? (Shouldn't happen due to ensured import below, but good for robustness)
                fixed = `import React, { ${hooksToMove.join(', ')} } from 'react';\n` + fixed;
            }
        }
    }

    // 2. Ensure React import is present
    if (!fixed.includes('import React')) {
        fixed = "import React from 'react';\n" + fixed;
        fixes.push('Added missing React import');
    }

    // 3. Check for required Remotion imports
    const requiredImports = ['AbsoluteFill', 'useCurrentFrame', 'useVideoConfig', 'interpolate'];
    const missingImports = requiredImports.filter(imp => !fixed.includes(imp));

    // Remove banned imports (spring nuclear option) — uses module-level BANNED_IMPORTS
    if (BANNED_IMPORTS.some(b => fixed.includes(b))) {
        fixed = fixed.replace(
            /import\s*\{([^}]+)\}\s*from\s*['"]remotion['"]/g,
            (match, existingImports) => {
                const existing = existingImports.split(',').map(s => s.trim()).filter(Boolean);
                const cleaned = existing.filter(i => !BANNED_IMPORTS.includes(i));
                return `import { ${cleaned.join(', ')} } from 'remotion'`;
            }
        );
        fixes.push('Scrubbed banned spring imports from remotion');
    }

    if (!fixed.includes('from \'remotion\'') && !fixed.includes('from "remotion"')) {
        fixed = `import { ${requiredImports.join(', ')} } from 'remotion';\n` + fixed;
        fixes.push('Added missing Remotion imports');
    } else if (missingImports.length > 0) {
        // Add missing imports to existing remotion import — never re-add banned symbols
        fixed = fixed.replace(
            /import\s*\{([^}]+)\}\s*from\s*['"]remotion['"]/,
            (match, existingImports) => {
                const existing = existingImports.split(',').map(s => s.trim()).filter(Boolean);
                const toAdd = missingImports.filter(i => !existing.includes(i) && !BANNED_IMPORTS.includes(i));
                if (toAdd.length === 0) return match;
                const combined = [...existing, ...toAdd];
                return `import { ${combined.join(', ')} } from 'remotion'`;
            }
        );
        fixes.push(`Added missing Remotion imports: ${missingImports.join(', ')}`);
    }

    // 4. Cleanup unwanted imports
    // Remove GSAP imports
    if (fixed.includes('gsap') || fixed.includes('GSAP')) {
        fixed = fixed.replace(/import.*gsap.*;\n?/gi, '');
        fixed = fixed.replace(/import.*GSAP.*;\n?/gi, '');
        fixes.push('Removed GSAP imports (use Remotion APIs)');
    }

    // Remove framer-motion imports
    if (fixed.includes('framer-motion')) {
        fixed = fixed.replace(/import.*framer-motion.*;\n?/gi, '');
        fixes.push('Removed framer-motion imports');
    }

    // Remove CSS module imports
    if (fixed.match(/import.*\.css['"]/)) {
        fixed = fixed.replace(/import.*\.css['"];\n?/g, '');
        fixes.push('Removed CSS import (use inline styles)');
    }

    return fixed;
}

// ====================================================================
// PHASE 3: COMPONENT STRUCTURE
// ====================================================================

function fixComponentStructure(code, fixes, warnings) {
    let fixed = code;

    // Ensure AnimationComponent is exported
    if (!fixed.includes('AnimationComponent')) {
        // Try to find any component and rename it
        const componentMatch = fixed.match(/export\s+(?:const|function)\s+(\w+)/);
        if (componentMatch) {
            const oldName = componentMatch[1];
            fixed = fixed.replace(new RegExp(`\\b${oldName}\\b`, 'g'), 'AnimationComponent');
            fixes.push(`Renamed component "${oldName}" → "AnimationComponent"`);
        } else {
            warnings.push('No AnimationComponent export found — may fail to render');
        }
    }

    // Ensure it's a named export (not default)
    if (fixed.includes('export default') && !fixed.includes('export const AnimationComponent') && !fixed.includes('export function AnimationComponent')) {
        fixed = fixed.replace('export default function', 'export const AnimationComponent = () =>');
        fixed = fixed.replace('export default', 'export');
        fixes.push('Converted default export to named export');
    }

    // Ensure export keyword is present
    if (fixed.includes('const AnimationComponent') && !fixed.includes('export const AnimationComponent') && !fixed.includes('export function AnimationComponent')) {
        fixed = fixed.replace('const AnimationComponent', 'export const AnimationComponent');
        fixes.push('Added export to AnimationComponent');
    }

    return fixed;
}

// ====================================================================
// PHASE 4: REMOTION API FIXES
// ====================================================================

function fixRemotionAPIs(code, fixes) {
    let fixed = code;

    // Fix fps expressions like "0.4 * fps" → "12"
    const fpsMatches = fixed.match(/(\d+\.?\d*)\s*\*\s*fps/g);
    if (fpsMatches) {
        fixed = fixed.replace(/(\d+\.?\d*)\s*\*\s*fps/g, (match, num) => {
            return String(Math.round(parseFloat(num) * 30));
        });
        fixes.push(`Resolved ${fpsMatches.length} fps expression(s) to static values`);
    }

    // Fix interpolate calls with missing outputRange (e.g. interpolate(frame, [0, 30]) — no 3rd arg)
    // This crashes with: "inputRange (2) and outputRange (undefined) must have the same length"
    let missingOutputFixes = 0;
    fixed = fixed.replace(
        /interpolate\s*\(\s*([^,]+),\s*\[([^\]]*)\]\s*\)/g,
        (match, frame, inputStr) => {
            // Only match if there's NO third argument (no outputRange)
            // Check there's not a trailing comma + more args after ]
            const inputs = inputStr.split(',').map(s => s.trim()).filter(Boolean);
            if (inputs.length < 2) return match; // Not a valid interpolate call
            missingOutputFixes++;
            // Default: map input range to [0, 1] (fade in)
            const outputRange = inputs.map((_, i) => i / (inputs.length - 1));
            return `interpolate(${frame}, [${inputStr}], [${outputRange.join(', ')}])`;
        }
    );
    if (missingOutputFixes > 0) {
        fixes.push(`Fixed ${missingOutputFixes} interpolate call(s) with missing outputRange (defaulted to [0, 1])`);
    }

    // Fix interpolate with variable references as outputRange (undefined at runtime)
    // e.g. interpolate(frame, [0, 30], outputValues) where outputValues might be undefined
    let varOutputFixes = 0;
    fixed = fixed.replace(
        /interpolate\s*\(\s*([^,]+),\s*\[([^\]]*)\]\s*,\s*([a-zA-Z_$][a-zA-Z0-9_$]*)\s*(?:,|\))/g,
        (match, frame, inputStr, varName) => {
            // If the variable name looks like a range identifier, it's likely undefined
            if (['outputRange', 'output', 'values', 'range', 'targets'].some(k => varName.toLowerCase().includes(k))) {
                const inputs = inputStr.split(',').map(s => s.trim()).filter(Boolean);
                const outputRange = inputs.map((_, i) => i / (inputs.length - 1));
                varOutputFixes++;
                const suffix = match.endsWith(',') ? ',' : ')';
                return `interpolate(${frame}, [${inputStr}], [${outputRange.join(', ')}]${suffix}`;
            }
            return match;
        }
    );
    if (varOutputFixes > 0) {
        fixes.push(`Fixed ${varOutputFixes} interpolate call(s) using undefined variable as outputRange`);
    }

    // Fix interpolate array length mismatches (common LLM mistake)
    let interpolateFixes = 0;
    fixed = fixed.replace(
        /interpolate\s*\(\s*([^,]+),\s*\[([^\]]*)\]\s*,\s*\[([^\]]*)\]\s*\)/g,
        (match, frame, inputStr, outputStr) => {
            const inputs = inputStr.split(',').map(s => s.trim()).filter(Boolean);
            const outputs = outputStr.split(',').map(s => s.trim()).filter(Boolean);
            if (inputs.length === outputs.length) return match;
            interpolateFixes++;
            if (inputs.length >= 2 && outputs.length >= 2) {
                return `interpolate(${frame}, [${inputs[0]}, ${inputs[inputs.length - 1]}], [${outputs[0]}, ${outputs[outputs.length - 1]}])`;
            }
            // If output is empty or has only 1 value, generate a default
            if (outputs.length === 0) {
                const defaultOutputs = inputs.map((_, i) => i / (inputs.length - 1));
                return `interpolate(${frame}, [${inputStr}], [${defaultOutputs.join(', ')}])`;
            }
            if (outputs.length === 1 && inputs.length >= 2) {
                return `interpolate(${frame}, [${inputs[0]}, ${inputs[inputs.length - 1]}], [0, ${outputs[0]}])`;
            }
            return match;
        }
    );
    if (interpolateFixes > 0) {
        fixes.push(`Fixed ${interpolateFixes} interpolate array mismatch(es)`);
    }

    // CRITICAL: Fix non-numeric values in interpolate outputRange
    // Remotion's interpolate() requires ONLY numbers in both inputRange and outputRange.
    // LLMs often generate: interpolate(frame, [0, 30], ['0px', '100px']) or ['0%', '100%']
    // This CRASHES with "outputRange must contain only numbers"
    let nonNumericFixes = 0;
    fixed = fixed.replace(
        /interpolate\s*\(\s*([^,]+),\s*\[([^\]]*)\]\s*,\s*\[([^\]]*)\]\s*\)/g,
        (match, frame, inputStr, outputStr) => {
            // Check if outputRange has any non-numeric values (strings with units like 'px', '%', 'deg')
            const outputs = outputStr.split(',').map(s => s.trim());
            const hasNonNumeric = outputs.some(o => /['"`]/.test(o) || /[a-zA-Z%]/.test(o.replace(/[-.\d\s]/g, '')));

            if (!hasNonNumeric) return match;

            // Extract numeric values from strings like '100px' → 100, '50%' → 50, '-20deg' → -20
            const cleanedOutputs = outputs.map(o => {
                // Remove quotes and extract number
                const cleaned = o.replace(/['"`]/g, '').trim();
                const numMatch = cleaned.match(/^(-?[\d.]+)/);
                return numMatch ? numMatch[1] : '0';
            });

            nonNumericFixes++;
            return `interpolate(${frame}, [${inputStr}], [${cleanedOutputs.join(', ')}])`;
        }
    );
    if (nonNumericFixes > 0) {
        fixes.push(`Fixed ${nonNumericFixes} interpolate outputRange(s) with non-numeric values (strings like 'px'/'%' stripped to numbers)`);
    }

    // Fix extrapolate: 'loop' → extrapolateRight: 'clamp'
    if (fixed.includes("extrapolate: 'loop'") || fixed.includes('extrapolate: "loop"')) {
        fixed = fixed.replace(/extrapolate:\s*['"]loop['"]/g, "extrapolateRight: 'clamp'");
        fixes.push("Fixed extrapolate: 'loop' → extrapolateRight: 'clamp'");
    }

    // Fix standalone 'loop' in interpolate options
    fixed = fixed.replace(/,\s*['"]loop['"]\s*\)/g, ", 'clamp')");

    // Fix broken syntax: interpolate(f, [i], [o]), { options } -> interpolate(f, [i], [o], { options })
    if (fixed.includes(']),')) {
        const before = fixed;
        // Match interpolate(...), { ... } and fix it
        fixed = fixed.replace(
            /(interpolate\s*\([^)]+\b)\]\),\s*\{([^}]+)\}/g,
            '$1], { $2 })'
        );
        if (fixed !== before) fixes.push('Fixed broken interpolate options syntax');
    }

    // Fix spring without fps parameter (common LLM mistake)
    // spring({ frame }) → spring({ frame, fps })
    const springWithoutFps = fixed.match(/spring\(\s*\{\s*frame\s*[,}]/g);
    if (springWithoutFps) {
        let springFixes = 0;
        fixed = fixed.replace(
            /spring\(\s*\{\s*frame\s*,\s*(?!fps)/g,
            (match) => {
                springFixes++;
                return match.replace('frame,', 'frame, fps,');
            }
        );
        fixed = fixed.replace(
            /spring\(\s*\{\s*frame\s*\}\s*\)/g,
            (match) => {
                springFixes++;
                return 'spring({ frame, fps })';
            }
        );
        if (springFixes > 0) fixes.push(`Added missing fps to ${springFixes} spring() call(s)`);
    }

    // Fix CSS `scale:` and `rotate:` standalone properties → `transform:` string
    // The CSS `scale` and `rotate` individual transform properties are too new for
    // Remotion's bundled Chromium. Gemini often generates them as style props:
    //   scale: scaleValue          → transform: `scale(${scaleValue})`
    //   rotate: angleValue         → transform: `rotate(${angleValue}deg)` (if numeric)
    // Use safeStyleReplace to only touch style props, not variable names.
    fixed = safeStyleReplace(fixed, 'div', (styles) => {
        if (!styles.match(/\bscale\s*:/) && !styles.match(/\brotate\s*:/)) return null;
        let changed = styles;
        let fixApplied = false;

        // scale: expr → transform: `scale(${expr})`
        changed = changed.replace(
            /\bscale\s*:\s*([^,\n]+?)(?=\s*,|\s*$)/g,
            (match, expr) => {
                const trimmed = expr.trim();
                // Skip if it looks like a string (already has quotes) — might be CSS 'scale(...)' value
                if (/^['"`]/.test(trimmed)) return match;
                fixApplied = true;
                return `transform: \`scale(\${${trimmed}})\``;
            }
        );

        if (!fixApplied) return null;
        fixes.push('Converted standalone scale: property to transform: `scale(${...})` (CSS scale not supported in Remotion Chromium)');
        return changed;
    });

    return fixed;
}

// ====================================================================
// PHASE 5: VISUAL / LAYOUT FIXES
// ====================================================================

/**
 * Safely injects new CSS properties into a style object's content string.
 *
 * Problem: if `cleanStyles` ends with a `//` line comment, naively appending
 * `, newProp` puts the new property inside the comment, and the closing `}}`
 * also gets swallowed — leaving the style object unclosed and crashing esbuild
 * with "Expected } but found style".
 *
 * Fix: detect a trailing `//` comment and push the new props onto the next line.
 */
function injectIntoStyles(cleanStyles, newProps) {
    if (!cleanStyles) return newProps;
    // If the last non-empty content is a // comment, newline before injecting
    if (/\/\/[^\n]*$/.test(cleanStyles)) {
        return `${cleanStyles}\n${newProps}`;
    }
    return `${cleanStyles}, ${newProps}`;
}

function fixLayout(code, fixes, settings = {}, warnings = []) {
    let fixed = code;

    // Detect whether this is an "absolute-positioning scene" where children use explicit
    // pixel coordinates (left/top in px) rather than flex flow.
    // If ≥3 elements use position:'absolute', skip adding padding & flex centering to the root
    // AbsoluteFill — adding them shifts the coordinate origin and pushes everything to the wrong spot.
    const absoluteElements = (fixed.match(/position:\s*['"]absolute['"]/g) || []).length;
    const isAbsoluteScene = absoluteElements >= 3;

    // CRITICAL: Ensure the outermost AbsoluteFill has centering styles (or absolute-scene base styles)
    // This is the #1 cause of off-center or invisible content
    const absFixPattern = /<AbsoluteFill((?![^>]*style=)[^>]*)>/;
    if (absFixPattern.test(fixed)) {
        fixed = fixed.replace(absFixPattern, (match, props) => {
            if (isAbsoluteScene) {
                // Absolute-positioning scene: no flex centering, no padding.
                // Children use explicit left/top pixel coords relative to the 1920×1080 canvas.
                // justifyContent/alignItems: flex-start prevents the validator from re-adding centering.
                // NOTE: do NOT add position:'relative' — AbsoluteFill is already position:absolute internally.
                return `<AbsoluteFill${props ? ' ' + props.trim() : ''} style={{
        overflow: 'hidden',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
      }}>`;
            }
            return `<AbsoluteFill${props ? ' ' + props.trim() : ''} style={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
        width: '100%',
        height: '100%',
        padding: '5% 8%',
        boxSizing: 'border-box',
        overflow: 'hidden'
      }}>`;
        });
        fixes.push(isAbsoluteScene
            ? 'Added absolute-scene base styles to root AbsoluteFill (no padding/centering — children use pixel coords)'
            : 'Added centering + safe area styles to root AbsoluteFill');
    }

    // Fix AbsoluteFills that have style but are missing centering
    // Non-greedy but smart: Look for style={{ and stop at the CORRECT matching }}
    let centeredFixes = 0;
    fixed = fixed.replace(
        /<AbsoluteFill\s+style=\{\{([\s\S]*?)\}\}(?![^}]*\})/g,
        (match, styles) => {
            if (styles.includes('justifyContent') && styles.includes('alignItems')) return match;

            // Check if we are inside a template literal interpolation
            if ((styles.match(/\$\{/g) || []).length !== (styles.match(/\}/g) || []).length) {
                return match; // Too complex for simple regex
            }

            const additions = [];
            if (isAbsoluteScene) {
                // For absolute scenes: use flex-start, no padding — preserve pixel coordinate system
                if (!styles.includes('overflow')) additions.push("overflow: 'hidden'");
                if (!styles.includes('justifyContent')) additions.push("justifyContent: 'flex-start'");
                if (!styles.includes('alignItems')) additions.push("alignItems: 'flex-start'");
            } else {
                if (!styles.includes('display')) additions.push("display: 'flex'");
                if (!styles.includes('flexDirection')) additions.push("flexDirection: 'column'");
                if (!styles.includes('justifyContent')) additions.push("justifyContent: 'center'");
                if (!styles.includes('alignItems')) additions.push("alignItems: 'center'");
                if (!styles.includes('textAlign')) additions.push("textAlign: 'center'");
                if (!styles.includes('padding')) additions.push("padding: '5% 8%'");
                if (!styles.includes('overflow')) additions.push("overflow: 'hidden'");
            }

            if (additions.length === 0) return match;

            centeredFixes++;
            const cleanStyles = styles.trimEnd().replace(/,?\s*$/, '');
            return `<AbsoluteFill style={{${injectIntoStyles(cleanStyles, additions.join(', '))}}}`;
        }
    );
    if (centeredFixes > 0) {
        fixes.push(`Added ${isAbsoluteScene ? 'overflow+flex-start' : 'centering'} to ${centeredFixes} AbsoluteFill element(s)`);
    }

    // Absolute-scene warning (informational — layout is intentional)
    if (isAbsoluteScene) {
        warnings.push(`Absolute-positioning scene detected (${absoluteElements} absolute elements) — skipped flex centering + padding on root to preserve pixel coordinate system`);
    }

    // CRITICAL CENTERING: Ensure ALL div containers with display:'flex' also have centering
    // Use a safe style-extraction approach that handles template literals and nested braces
    let divCenterFixes = 0;
    fixed = safeStyleReplace(fixed, 'div', (styles) => {
        if (!styles.includes('display')) return null;
        if (!styles.includes('flex')) return null;
        if (styles.includes('alignItems') && styles.includes('textAlign')) return null;

        divCenterFixes++;
        const cleanStyles = styles.trimEnd().replace(/,?\s*$/, '');
        return injectIntoStyles(cleanStyles, "alignItems: 'center', textAlign: 'center'");
    });
    if (divCenterFixes > 0) {
        fixes.push(`Added centering to ${divCenterFixes} inner flex container(s)`);
    }

    // Ensure ALL text-containing elements have textAlign: 'center'
    // Match <div style={{...}}> that contain text-related styles (fontSize, fontWeight, color)
    // but are missing textAlign
    let textAlignFixes = 0;
    fixed = safeStyleReplace(fixed, 'div', (styles) => {
        if (!styles.includes('fontSize') && !styles.includes('fontWeight') && !styles.includes('letterSpacing')) return null;
        if (styles.includes('textAlign')) return null;

        textAlignFixes++;
        const cleanStyles = styles.trimEnd().replace(/,?\s*$/, '');
        return injectIntoStyles(cleanStyles, "textAlign: 'center'");
    });
    if (textAlignFixes > 0) {
        fixes.push(`Added textAlign: 'center' to ${textAlignFixes} text element(s)`);
    }

    // Fix width percentages < 100% on main content containers that cause off-center appearance
    // If a div has width: '80%' or similar, ensure it also has margin: '0 auto' for horizontal centering
    let marginAutoFixes = 0;
    fixed = safeStyleReplace(fixed, 'div', (styles) => {
        if (!styles.includes('width')) return null;
        if (!styles.includes('%')) return null;
        if (styles.includes('margin')) return null; // Already has margin

        marginAutoFixes++;
        const cleanStyles = styles.trimEnd().replace(/,?\s*$/, '');
        return injectIntoStyles(cleanStyles, "margin: '0 auto'");
    });
    if (marginAutoFixes > 0) {
        fixes.push(`Added margin: '0 auto' to ${marginAutoFixes} partial-width container(s)`);
    }

    // Ensure root container has a background color (prevent transparent/invisible output)
    // Check broadly — backgroundColor, background, bgColor, or any hex color in the root style
    const hasAnyBackground = fixed.includes('backgroundColor') || fixed.includes("background:") ||
        fixed.includes("background '") || fixed.includes('background "') ||
        fixed.includes('background:') || fixed.includes('linearGradient') ||
        fixed.includes('linear-gradient');
    if (!hasAnyBackground) {
        // Add a default dark background to the first AbsoluteFill
        fixed = fixed.replace(
            /(<AbsoluteFill[^>]*style=\{\{)/,
            "$1 backgroundColor: '#0a0a0a',"
        );
        fixes.push('Added dark background color (#0a0a0a) to prevent transparent output');
    }

    return fixed;
}

// ====================================================================
// PHASE 6: TYPOGRAPHY & STYLING
// ====================================================================

function fixTypography(code, fixes, settings = {}, warnings = []) {
    let fixed = code;
    const font = settings.font || 'Inter';

    // Ensure no font-size is too small (< 18px is unreadable in video)
    fixed = safeStyleReplace(fixed, '*', (styles) => {
        let changed = false;
        const newStyles = styles.replace(/fontSize:\s*['"]?(\d+(?:\.\d+)?)(?:px)?['"]?/g, (match, size) => {
            const px = parseFloat(size);
            if (px < 18 && px > 0) {
                changed = true;
                return `fontSize: 24`;
            }
            return match;
        });
        if (changed) smallFontFixes++;
        return newStyles;
    });
    if (smallFontFixes > 0) {
        fixes.push(`Increased font size(s) below 18px to 24px for video readability`);
    }

    // Ensure text has enough contrast — white text on dark bg or vice versa
    // If we find light text (#fff, white) with light background, warn
    const hasWhiteText = fixed.includes("'#FFFFFF'") || fixed.includes("'#ffffff'") || fixed.includes("'#FFF'") || fixed.includes("'white'");
    const hasLightBg = fixed.includes("'#FFFFFF'") && fixed.includes("backgroundColor: '#FFFFFF'");
    if (hasLightBg && hasWhiteText) {
        warnings.push('Possible contrast issue: white text on white background detected');
    }

    // Ensure fontFamily is set on root for consistent typography
    if (!fixed.includes('fontFamily')) {
        // Only add to the FIRST AbsoluteFill (root), not nested ones
        let fontAdded = false;
        fixed = fixed.replace(
            /(<AbsoluteFill[^>]*style=\{\{)/,
            (match) => {
                if (fontAdded) return match;
                fontAdded = true;
                return `${match} fontFamily: "'${font}', system-ui, -apple-system, sans-serif",`;
            }
        );
        if (fontAdded) fixes.push(`Added fontFamily "${font}" to root element`);
    }

    // Fix text not being visible: if opacity: 0 is set without animation
    // This catches cases where LLM sets opacity: 0 but forgets to animate it
    const opacityZero = fixed.match(/opacity:\s*0[^.]/g);
    const hasOpacityAnim = fixed.includes('interpolate') && fixed.includes('opacity');
    if (opacityZero && opacityZero.length > 3 && !hasOpacityAnim) {
        warnings.push(`Found ${opacityZero.length} elements with opacity: 0 but no opacity animation — content may be invisible`);
    }

    // Ensure lineHeight is set on headings for proper vertical spacing
    // Fix tight lineHeight (< 1.0) that clips text
    fixed = fixed.replace(/lineHeight:\s*['"]?(0\.\d+)['"]?/g, (match, val) => {
        if (parseFloat(val) < 0.9) {
            fixes.push(`Fixed tight lineHeight ${val} → 1.1`);
            return 'lineHeight: 1.1';
        }
        return match;
    });

    return fixed;
}

// ====================================================================
// PHASE 7: ANIMATION QUALITY
// ====================================================================

function fixAnimations(code, fixes, warnings) {
    let fixed = code;

    // Warn if no animation is present (static scene)
    if (!fixed.includes('useCurrentFrame') && !fixed.includes('interpolate') && !fixed.includes('spring')) {
        warnings.push('No animations detected — scene will be completely static');
    }

    // Fix spring configs with extreme values that cause jitter
    fixed = fixed.replace(
        /stiffness:\s*(\d+)/g,
        (match, val) => {
            const v = parseInt(val);
            if (v > 400) {
                fixes.push(`Capped spring stiffness from ${v} to 300 (prevents jitter)`);
                return 'stiffness: 300';
            }
            if (v < 10) {
                fixes.push(`Raised spring stiffness from ${v} to 40 (prevents sluggish animation)`);
                return 'stiffness: 40';
            }
            return match;
        }
    );

    fixed = fixed.replace(
        /damping:\s*(\d+)/g,
        (match, val) => {
            const v = parseInt(val);
            if (v > 100) {
                fixes.push(`Capped spring damping from ${v} to 80 (prevents over-damping)`);
                return 'damping: 80';
            }
            if (v < 3) {
                fixes.push(`Raised spring damping from ${v} to 8 (prevents excessive bounce)`);
                return 'damping: 8';
            }
            return match;
        }
    );

    // Warn if animations reference frame numbers > 300 (default duration)
    const largeFrameRefs = fixed.match(/\[\s*\d{4,}/g);
    if (largeFrameRefs) {
        warnings.push(`Found frame references > 999 — ensure duration matches (may cause animations to never complete)`);
    }

    return fixed;
}

// ====================================================================
// PHASE 8: SEQUENCE SAFETY
// ====================================================================

function fixSequenceSafety(code, fixes, warnings) {
    let fixed = code;

    // CRITICAL: Sequence with durationInFrames causes content to UNMOUNT after duration
    // This is the #1 cause of black screens in generated animations
    const sequenceCount = (fixed.match(/<Sequence/g) || []).length;

    if (sequenceCount > 0) {
        // Check if any Sequence wraps ALL content (causes black screen at end)
        const hasMainWrapper = fixed.match(/<Sequence[^>]*durationInFrames=\{?\d+\}?[^>]*>[\s\S]*<\/Sequence>\s*$/);
        if (hasMainWrapper) {
            warnings.push('Sequence wrapping ALL content with durationInFrames — will cause black screen after duration');
        }

        // Check for Sequence without from prop (defaults to 0, may overlap)
        const sequencesWithoutFrom = fixed.match(/<Sequence(?![^>]*from=)/g);
        if (sequencesWithoutFrom && sequencesWithoutFrom.length > 1) {
            warnings.push(`${sequencesWithoutFrom.length} Sequences without "from" prop — may cause overlapping content`);
        }
    }

    // If there are many Sequences and the total durationInFrames don't add up, warn
    const durations = [];
    fixed.replace(/durationInFrames=\{?(\d+)\}?/g, (match, d) => {
        durations.push(parseInt(d));
        return match;
    });
    if (durations.length > 1) {
        const totalDuration = Math.max(...durations);
        if (totalDuration < 120) {
            warnings.push(`Max Sequence duration is only ${totalDuration} frames — animation may end prematurely (recommend 300 frames)`);
        }
    }

    return fixed;
}

/**
 * Quick validation that returns only a pass/fail + issue list (no fixes applied).
 * Useful for the frontend to show warnings before generation.
 */
export function quickValidate(code) {
    const issues = [];

    if (!code.includes('AnimationComponent')) issues.push('Missing AnimationComponent export');
    if (!code.includes('remotion')) issues.push('Missing Remotion imports');
    if (!code.includes('useCurrentFrame')) issues.push('No frame-based animation detected');

    // Check for common black-screen causes
    if (code.includes('<Sequence') && code.includes('durationInFrames')) {
        issues.push('Uses Sequence with durationInFrames — may cause black screens');
    }

    // Check for centering
    const hasCenter = code.includes('justifyContent') && code.includes('alignItems');
    if (!hasCenter) issues.push('Content may not be centered');

    // Check for background
    if (!code.includes('backgroundColor') && !code.includes('background')) {
        issues.push('No background color — output may be transparent');
    }

    return {
        valid: issues.length === 0,
        issues
    };
}

// ====================================================================
// PHASE 0: STRIP TRAILING NON-CODE GARBAGE
// ====================================================================

function stripTrailingGarbage(code, fixes) {
    let fixed = code;

    // Strip stray bare quote characters after closing braces — Gemini artifact.
    // e.g. `};"` at end of a line: the " opens an unterminated string that crashes esbuild.
    // `};"` → `};`  |  `},"` → `},`  |  `}` followed by lone " → `}`
    // This runs before the line-walk so the line-walk doesn't see `};"` as "valid code".
    const beforeQuoteStrip = fixed;
    fixed = fixed.replace(/^(\s*\}[;,]?)\s*["'`]\s*$/gm, '$1');
    if (fixed !== beforeQuoteStrip) {
        fixes.push('Stripped stray bare quote after closing brace (e.g. `};"` → `};`)');
    }

    // Find the last valid code boundary: the last `};` or `}` that closes the component
    // Then strip anything after it that isn't valid JS (e.g. Chinese characters, random text)
    // We look for the last line that ends with }; or } or /> or </SomeTag>
    const lines = fixed.split('\n');
    let lastValidLine = lines.length - 1;

    // Walk backwards from the end to find trailing garbage
    for (let i = lines.length - 1; i >= 0; i--) {
        const trimmed = lines[i].trim();
        if (trimmed === '') continue; // skip blank lines

        // Check if this line looks like valid code
        const isValidCode = /^[\s{}();,/\[\]<>=:'"`.+\-*&|!?~%^@#$_a-zA-Z0-9\\]/.test(trimmed) &&
            !/^[^\x00-\x7F]+$/.test(trimmed); // Not entirely non-ASCII

        // Check for heavily truncated/hanging expressions like `const start4 = end`
        // Match: (const/let/var) (spaces) (variableName) (optional spacing) (optional = and remaining text)
        // Kept simple to avoid catastrophic backtracking
        const isHangingAssignment = /^(?:const|let|var)\s+[a-zA-Z0-9_$]+(?:\s*=\s*[a-zA-Z0-9_$]*)?$/.test(trimmed);

        if (isValidCode && !isHangingAssignment) {
            lastValidLine = i;
            break;
        } else {
            // This line is garbage or a hanging assignment
            lastValidLine = i - 1;
        }
    }

    if (lastValidLine < lines.length - 1) {
        const removed = lines.slice(lastValidLine + 1).join('\n').trim();
        if (removed.length > 0) {
            fixed = lines.slice(0, lastValidLine + 1).join('\n');
            fixes.push(`Stripped trailing non-code or hanging assignments: "${removed.substring(0, 30)}..."`);
        }
    }

    return fixed;
}

// ====================================================================
// PHASE 1.3: TEMPLATE LITERAL FIX
// ====================================================================

/**
 * Fixes broken template literals — the #1 source of Gemini syntax errors.
 *
 * Common patterns that break:
 * 1. Extra closing brace: `translateY(${value}}px)` → `translateY(${value}px)`
 * 2. Garbage in interpolation: `scale(${val, foo: 'bar'}})` → `scale(${val})`
 * 3. Mangled ternary: `${frame }}}> 10 ? 'a' : 'b'}` → `${frame > 10 ? 'a' : 'b'}`
 * 4. Extra brace after variable: `${COLORS.red}}, transparent)` → `${COLORS.red}, transparent)`
 */
function fixTemplateLiterals(code, fixes) {
    let fixed = code;
    let fixCount = 0;

    // Pattern 1: Double/triple closing braces after interpolation: ${...}}  or  ${...}}}
    // Match ${...} followed by extra } that aren't part of an object literal
    // We need to be careful not to break style={{ }} patterns
    const beforeP1 = fixed;
    fixed = fixed.replace(/(\$\{[^}]*\})\}(?!\s*\)|\s*,\s*['"]|\s*;)/g, (match, interpolation) => {
        // Check if this is inside a template literal by looking at surrounding context
        // Only fix if we're clearly inside a backtick string
        fixCount++;
        return interpolation;
    });

    // Pattern 2: Extra } after template literal interpolation that references an object property
    // e.g., ${COLORS.crimson}}, transparent) → ${COLORS.crimson}, transparent)
    // e.g., ${COLORS.accent}}1px → ${COLORS.accent} 1px
    fixed = fixed.replace(/(\$\{[\w.]+\})\}(?=[\s,)1-9a-z])/g, (match, interpolation) => {
        fixCount++;
        return interpolation;
    });

    // Pattern 3: Garbage object properties injected into interpolations
    // e.g., ${finalPulse, alignItems: 'center', textAlign: 'center'}} → ${finalPulse}
    // Match ${identifier followed by comma and what looks like CSS properties
    fixed = fixed.replace(/\$\{(\w+(?:\.\w+)?)\s*,\s*(?:\w+:\s*['"][^'"]*['"],?\s*)+\}+/g, (match, varName) => {
        fixCount++;
        return '${' + varName + '}';
    });

    // Pattern 4: Mangled ternaries with extra braces
    // e.g., ${frame }}}> 110 ? 'rgba(...)' : 'transparent'} → ${frame > 110 ? 'rgba(...)' : 'transparent'}
    fixed = fixed.replace(/\$\{(\w+)\s*\}{2,}>\s*(\d+)\s*\?\s*('[^']*'|"[^"]*")\s*:\s*('[^']*'|"[^"]*")\s*\}?\)/g,
        (match, varName, num, trueVal, falseVal) => {
            fixCount++;
            return '${' + varName + ' > ' + num + ' ? ' + trueVal + ' : ' + falseVal + '})';
        }
    );

    // Pattern 5: Broken filter/transform with mangled template literals
    // Detect lines with backtick strings that have obviously mismatched ${...} and extra }
    // Uses a STACK to properly handle plain {…} inside ${…} expressions (e.g. interpolate options).
    // Previous depth-counter approach treated the } of { extrapolateRight: 'clamp' } as closing
    // the ${…}, which stripped the real closing } and broke the template literal.
    fixed = fixed.replace(/`([^`]*)`/g, (match, content) => {
        // stack entries: '$' = opened by ${ (template interpolation), '{' = opened by plain {
        const stack = [];
        let cleaned = '';

        for (let i = 0; i < content.length; i++) {
            // Start of template interpolation: ${
            if (content[i] === '$' && content[i + 1] === '{') {
                stack.push('$');
                cleaned += '${';
                i++; // skip the { that's part of ${
                continue;
            }
            // Plain { only counts when we're already inside a template expression
            if (content[i] === '{' && stack.length > 0) {
                stack.push('{');
                cleaned += '{';
                continue;
            }
            if (content[i] === '}') {
                if (stack.length > 0) {
                    stack.pop();   // close whichever bracket is on top (${ or plain {)
                    cleaned += '}';
                } else {
                    // Extra closing brace with nothing open — skip it
                    fixCount++;
                }
                continue;
            }
            cleaned += content[i];
        }

        if (cleaned !== content) {
            return '`' + cleaned + '`';
        }
        return match;
    });

    // Pattern 6: Double/triple }} before > in ternary expressions OUTSIDE template literals
    // Gemini produces: `highlightProgress }}> 0 ? AMBER : color,`
    // Should be: `highlightProgress > 0 ? AMBER : color,`
    const beforeP6 = fixed;
    fixed = fixed.replace(/(\w+)\s*\}{2,}>\s*(\d)/g, (match, varName, num) => {
        fixCount++;
        return `${varName} > ${num}`;
    });

    if (fixCount > 0) {
        fixes.push(`Fixed ${fixCount} broken template literal(s) (extra braces, mangled interpolations)`);
    }

    return fixed;
}

// ====================================================================
// PHASE 1.5: STRING LITERAL FIX
// ====================================================================

/**
 * Detects single/double-quoted strings that contain raw newline characters
 * (i.e. the string literal spans multiple source lines without using a template literal).
 * esbuild hard-errors on these: "Unterminated string literal".
 *
 * Fix: convert them to template literals. Template literals support raw newlines.
 * Apostrophes inside double-quoted strings (e.g. "isn't") are handled correctly because
 * we scan character-by-character and only close on the MATCHING quote character.
 *
 * Common LLM pattern that triggers this:
 *   const chart = "graph LR
 *       A --> B";        ← raw \n inside "..." → esbuild error
 * Becomes:
 *   const chart = `graph LR
 *       A --> B`;        ← template literal → valid
 */
function fixUnterminatedStrings(code, fixes) {
    let result = '';
    let i = 0;
    let fixCount = 0;

    while (i < code.length) {
        const ch = code[i];

        // Skip template literals verbatim — they already handle raw newlines
        if (ch === '`') {
            result += ch;
            i++;
            while (i < code.length) {
                if (code[i] === '\\') {
                    result += code[i] + (code[i + 1] || '');
                    i += 2;
                } else if (code[i] === '`') {
                    result += '`';
                    i++;
                    break;
                } else {
                    result += code[i++];
                }
            }
            continue;
        }

        // Skip single-line // comments
        if (ch === '/' && code[i + 1] === '/') {
            while (i < code.length && code[i] !== '\n') result += code[i++];
            continue;
        }

        // Skip /* ... */ comments
        if (ch === '/' && code[i + 1] === '*') {
            result += code[i++] + code[i++]; // /*
            while (i < code.length) {
                if (code[i] === '*' && code[i + 1] === '/') { result += '*/'; i += 2; break; }
                result += code[i++];
            }
            continue;
        }

        // Single or double-quoted strings — scan to find raw newlines
        if (ch === "'" || ch === '"') {
            const quote = ch;
            let strContent = '';
            let hasRawNewline = false;
            let j = i + 1;

            while (j < code.length) {
                const sc = code[j];
                if (sc === '\\') {
                    // Escaped character — consume both chars
                    strContent += code[j] + (code[j + 1] || '');
                    j += 2;
                    continue;
                }
                if (sc === '\n' || sc === '\r') {
                    // Raw newline inside a quoted string → this IS the bug
                    hasRawNewline = true;
                    strContent += sc;
                    j++;
                    continue;
                }
                if (sc === quote) {
                    // String closed normally
                    j++;
                    break;
                }
                strContent += sc;
                j++;
            }

            if (hasRawNewline) {
                // Convert to template literal:
                // escape any literal backticks and ${ that would be misinterpreted
                const templateContent = strContent
                    .replace(/`/g, '\\`')
                    .replace(/\$\{/g, '\\${');
                result += '`' + templateContent + '`';
                fixCount++;
            } else {
                // Normal single-line string — emit as-is
                // j is now one past the closing quote (or at code.length if unterminated)
                const closingQuote = j <= code.length && code[j - 1] === quote ? quote : '';
                result += quote + strContent + closingQuote;
            }
            i = j;
            continue;
        }

        result += code[i++];
    }

    if (fixCount > 0) {
        fixes.push(`Converted ${fixCount} multi-line string literal(s) to template literals (raw newline in "..." → "Unterminated string literal" esbuild error)`);
    }

    return result;
}

// ====================================================================
// PHASE 1.6: JSX TAG FIX
// ====================================================================

function fixUnclosedTags(code, fixes) {
    let fixed = code;
    // Match unclosed tags at the end of lines or followed by { that never close
    // This is a heuristic for truncated or malformed tags
    const before = fixed;

    // 1. Tags that end with a word and a space but no > (e.g. <div style={{...} )
    // We already improved balancer.js to handle this, but let's add a more aggressive cleanup here

    // 3. Remove standalone < characters at the end of the line if they don't start a valid tag
    fixed = fixed.replace(/<[ \t]*\n/g, '\n');

    if (fixed !== before) {
        fixes.push('Fixed malformed JSX tags/attributes');
    }
    return fixed;
}

// ====================================================================
// PHASE 5.1: BACKGROUND SHORTHAND FIX
// ====================================================================

/**
 * Problem 3: The background: CSS shorthand silently breaks gradient rendering in Remotion.
 * - background: 'linear-gradient(...)' → backgroundImage: 'linear-gradient(...)'
 * - background: '#hex' → backgroundColor: '#hex'
 * - background: 'rgba(...)' → backgroundColor: 'rgba(...)'
 * - background: 'named-color' → backgroundColor: 'named-color'
 *
 * Note: For elements with WebkitBackgroundClip (text gradient effect), we intentionally
 * omit the backgroundColor fallback to avoid interfering with the text clip effect.
 */
function fixBackgroundShorthand(code, fixes) {
    let fixed = code;
    let fixCount = 0;

    // Fix gradient shorthands (linear/radial/conic) — single quotes
    for (const gradType of ['linear-gradient', 'radial-gradient', 'conic-gradient']) {
        fixed = fixed.replace(
            new RegExp(`\\bbackground:\\s*'(${gradType}[^']*)'`, 'g'),
            (match, gradient) => {
                fixCount++;
                return `backgroundImage: '${gradient}'`;
            }
        );
        // Double quotes
        fixed = fixed.replace(
            new RegExp(`\\bbackground:\\s*"(${gradType}[^"]*)"`, 'g'),
            (match, gradient) => {
                fixCount++;
                return `backgroundImage: "${gradient}"`;
            }
        );
    }

    // Fix solid hex color shorthand: background: '#xxx' → backgroundColor: '#xxx'
    fixed = fixed.replace(/\bbackground:\s*'(#[0-9a-fA-F]{3,8})'/g, (match, hex) => {
        fixCount++;
        return `backgroundColor: '${hex}'`;
    });
    fixed = fixed.replace(/\bbackground:\s*"(#[0-9a-fA-F]{3,8})"/g, (match, hex) => {
        fixCount++;
        return `backgroundColor: "${hex}"`;
    });

    // Fix rgba/rgb/hsl color shorthand → backgroundColor
    fixed = fixed.replace(/\bbackground:\s*'((?:rgba?|hsla?)\([^']*\))'/g, (match, color) => {
        fixCount++;
        return `backgroundColor: '${color}'`;
    });
    fixed = fixed.replace(/\bbackground:\s*"((?:rgba?|hsla?)\([^"]*\))"/g, (match, color) => {
        fixCount++;
        return `backgroundColor: "${color}"`;
    });

    // Fix named colors → backgroundColor
    const namedColors = 'black|white|transparent|red|blue|green|yellow|purple|orange|gray|grey|navy|teal|maroon|silver|aqua|lime|fuchsia|olive|cyan|magenta|pink|brown|crimson|gold|indigo|violet|coral|salmon|turquoise|lavender';
    fixed = fixed.replace(
        new RegExp(`\\bbackground:\\s*'(${namedColors})'`, 'g'),
        (match, color) => { fixCount++; return `backgroundColor: '${color}'`; }
    );

    if (fixCount > 0) {
        fixes.push(`Fixed ${fixCount} background: shorthand(s) → backgroundImage:/backgroundColor: (prevents silent gradient rendering failure in Remotion)`);
    }

    return fixed;
}

// ====================================================================
// PHASE 5.2b: INTERPOLATE() CLAMP INJECTION
// ====================================================================

/**
 * Injects extrapolateLeft: 'clamp', extrapolateRight: 'clamp' into every
 * interpolate() call that is missing one or both of those options.
 *
 * Root cause: without clamps, when frame reaches durationInFrames exactly,
 * interpolate() extrapolates past the output range, potentially producing NaN
 * or Infinity on a geometry/style property — which kills the WebGL context
 * and causes the "Target closed" renderer crash at the 80–100% progress point.
 *
 * Handles all forms:
 *   interpolate(frame, [...], [...])                   → adds { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }
 *   interpolate(frame, [...], [...], { ... })          → injects missing keys
 *   interpolate(frame, [...], [...], { extrapolateRight: 'clamp' }) → adds extrapolateLeft too
 */
function clampInterpolates(code, fixes) {
    if (!code.includes('interpolate(')) return code;

    let result = '';
    let i = 0;
    let clampFixes = 0;

    while (i < code.length) {
        const idx = code.indexOf('interpolate(', i);
        if (idx === -1) {
            result += code.slice(i);
            break;
        }

        result += code.slice(i, idx);

        // Parse the full interpolate(...) call by counting parens
        const start = idx + 'interpolate('.length;
        let depth = 1;
        let j = start;
        while (j < code.length && depth > 0) {
            if (code[j] === '(') depth++;
            else if (code[j] === ')') depth--;
            j++;
        }
        const innerContent = code.slice(start, j - 1); // content inside outer parens
        const fullCall = code.slice(idx, j);

        // Split into top-level arguments (respecting nested parens/brackets/braces)
        const args = [];
        let argStart = 0;
        let d = 0;
        for (let k = 0; k < innerContent.length; k++) {
            const c = innerContent[k];
            if (c === '(' || c === '[' || c === '{') d++;
            else if (c === ')' || c === ']' || c === '}') d--;
            else if (c === ',' && d === 0) {
                args.push(innerContent.slice(argStart, k).trim());
                argStart = k + 1;
            }
        }
        args.push(innerContent.slice(argStart).trim());

        // Must have at least 3 args (frame, inputRange, outputRange)
        if (args.length < 3) {
            result += fullCall;
            i = j;
            continue;
        }

        let optionsArg = args[3] || null;
        let needsLeft = true;
        let needsRight = true;

        if (optionsArg) {
            if (optionsArg.includes('extrapolateLeft')) needsLeft = false;
            if (optionsArg.includes('extrapolateRight')) needsRight = false;
        }

        if (!needsLeft && !needsRight) {
            // Already fully clamped
            result += fullCall;
            i = j;
            continue;
        }

        clampFixes++;

        let newOptions;
        if (!optionsArg) {
            newOptions = `{ extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }`;
        } else {
            // Inject missing keys into the existing options object
            let opts = optionsArg.trim();
            // Strip outer braces
            const inner = opts.replace(/^\{/, '').replace(/\}$/, '').trim();
            const additions = [];
            if (needsLeft) additions.push(`extrapolateLeft: 'clamp'`);
            if (needsRight) additions.push(`extrapolateRight: 'clamp'`);
            const separator = inner.length > 0 ? ', ' : '';
            newOptions = `{ ${inner}${separator}${additions.join(', ')} }`;
        }

        const newArgs = [...args.slice(0, 3), newOptions];
        result += `interpolate(${newArgs.join(', ')})`;
        i = j;
    }

    if (clampFixes > 0) {
        fixes.push(`Phase 5.2b: Added extrapolateLeft/Right: 'clamp' to ${clampFixes} interpolate() call(s) — prevents NaN/Infinity WebGL crash at frame boundaries`);
    }

    return result;
}

// ====================================================================
// PHASE 5.2: SPRING() BAN — REPLACE WITH INTERPOLATE()
// ====================================================================

/**
 * Problem 4/5: spring() crashes with "Frame NaN is not finite" in this pipeline.
 * Replace EVERY spring() call with interpolate() + Math.min/max clamping.
 *
 * Handles common patterns:
 *   spring({ frame, fps, config: { ... } })
 *   → Math.min(1, Math.max(0, interpolate(frame, [0, 30], [0, 1], { extrapolateRight: 'clamp' })))
 *
 *   spring({ frame: frame - N, fps, ... })
 *   → Math.min(1, Math.max(0, interpolate(frame, [N, N+30], [0, 1], { extrapolateRight: 'clamp' })))
 *
 *   spring({ frame, fps, from: A, to: B, ... })
 *   → Math.min(B, Math.max(A, interpolate(frame, [0, 30], [A, B], { extrapolateRight: 'clamp' })))
 */
function replaceSpringWithInterpolate(code, fixes) {
    if (!code.includes('spring(')) return code;

    let result = '';
    let i = 0;
    let springFixes = 0;

    while (i < code.length) {
        const idx = code.indexOf('spring(', i);
        if (idx === -1) {
            result += code.slice(i);
            break;
        }

        // Ensure 'spring' is a standalone identifier (not 'offspring', 'springConfig', '.spring(')
        if (idx > 0 && /[\w.]/.test(code[idx - 1])) {
            result += code.slice(i, idx + 1);
            i = idx + 1;
            continue;
        }

        result += code.slice(i, idx);

        // Find the matching ) using depth counting
        const argsStart = idx + 'spring('.length;
        let depth = 1;
        let j = argsStart;
        let inStr = null;

        while (j < code.length && depth > 0) {
            const ch = code[j];
            if (!inStr) {
                if (ch === '"' || ch === "'" || ch === '`') {
                    inStr = ch;
                } else if (ch === '(' || ch === '{' || ch === '[') {
                    depth++;
                } else if (ch === ')' || ch === '}' || ch === ']') {
                    depth--;
                }
            } else {
                if (ch === '\\') {
                    j++; // skip escaped char
                } else if (ch === inStr && inStr !== '`') {
                    inStr = null;
                } else if (inStr === '`' && ch === '`') {
                    inStr = null;
                }
            }
            if (depth > 0) j++;
            else break;
        }
        // j now points at the closing )
        j++; // move past )

        // Delay-aware replacement: parse spring() args to preserve frame offset,
        // from/to range, and stiffness-derived duration before substituting interpolate().
        const argsContent = code.slice(argsStart, j - 1);

        let frameExpr = 'frame';
        let fromVal = 0;
        let toVal = 1;
        let durationFrames = 25;

        // Extract frame: expression (handles `frame`, `frame - delay`, `frame - 10`)
        const frameMatch = argsContent.match(/\bframe\s*:\s*([^,}]+)/);
        if (frameMatch) frameExpr = frameMatch[1].trim();

        // Extract from: and to: values
        const fromMatch = argsContent.match(/\bfrom\s*:\s*([\d.]+)/);
        const toMatch   = argsContent.match(/\bto\s*:\s*([\d.]+)/);
        if (fromMatch) fromVal = parseFloat(fromMatch[1]);
        if (toMatch)   toVal   = parseFloat(toMatch[1]);

        // Approximate animation duration from stiffness (higher = faster)
        const stiffMatch = argsContent.match(/\bstiffness\s*:\s*([\d.]+)/);
        if (stiffMatch) {
            const s = parseFloat(stiffMatch[1]);
            durationFrames = s >= 200 ? 12 : s >= 100 ? 20 : 30;
        }

        // If frame expression has an offset (e.g. frame - delay), shift the input range
        let startFrame = '0';
        const offsetMatch = frameExpr.match(/frame\s*-\s*([\w.]+)/);
        if (offsetMatch) {
            startFrame = offsetMatch[1]; // e.g. "delay" or "10"
            frameExpr  = 'frame';
        }

        const inputEnd = startFrame !== '0'
            ? `(${startFrame}) + ${durationFrames}`
            : String(durationFrames);

        const replacement = `Math.min(${toVal}, Math.max(${fromVal}, interpolate(${frameExpr}, [${startFrame}, ${inputEnd}], [${fromVal}, ${toVal}], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' })))`;

        result += replacement;
        i = j;
        springFixes++;
    }

    if (springFixes > 0) {
        fixes.push(`Nuclear Option: Replaced ${springFixes} spring() call(s) entirely with clamped interpolate()`);
    }

    return result;
}

// ====================================================================
// PHASE 5.3: RIGHT/BOTTOM → LEFT/TOP POSITIONING FIX
// ====================================================================

/**
 * Problem 7/13: right: and bottom: CSS properties can behave unexpectedly.
 * Where width/height are known in the same style block, convert:
 *   right: N  → left: (canvasWidth - elementWidth - N)
 *   bottom: N → top: (canvasHeight - elementHeight - N)
 */
function fixRightBottomPositioning(code, fixes, settings = {}) {
    const isPortrait = settings.format === 'portrait' || settings.format === 'tiktok';
    const canvasW = isPortrait ? 1080 : 1920;
    const canvasH = isPortrait ? 1920 : 1080;

    let fixCount = 0;

    const fixed = safeStyleReplace(code, 'div', (styles) => {
        if (!styles.includes('right:') && !styles.includes('bottom:')) return null;

        let newStyles = styles;
        let changed = false;

        // right: N → left: (canvasW - width - N)
        const rightMatch = styles.match(/\bright:\s*(-?[\d.]+)(?!\s*['"%])/);
        if (rightMatch) {
            const rightVal = parseFloat(rightMatch[1]);
            // Only convert if width is also a plain pixel value in the same style block
            const widthMatch = styles.match(/\bwidth:\s*([\d.]+)(?!\s*['"%])/);
            if (widthMatch) {
                const w = parseFloat(widthMatch[1]);
                const leftVal = Math.round(canvasW - w - rightVal);
                newStyles = newStyles.replace(/\bright:\s*-?[\d.]+(?!\s*['"%])/, `left: ${leftVal}`);
                changed = true;
                fixCount++;
            }
        }

        // bottom: N → top: (canvasH - height - N)
        const bottomMatch = styles.match(/\bbottom:\s*(-?[\d.]+)(?!\s*['"%])/);
        if (bottomMatch) {
            const bottomVal = parseFloat(bottomMatch[1]);
            const heightMatch = styles.match(/\bheight:\s*([\d.]+)(?!\s*['"%])/);
            if (heightMatch) {
                const h = parseFloat(heightMatch[1]);
                const topVal = Math.round(canvasH - h - bottomVal);
                newStyles = newStyles.replace(/\bbottom:\s*-?[\d.]+(?!\s*['"%])/, `top: ${topVal}`);
                changed = true;
                fixCount++;
            }
        }

        return changed ? newStyles : null;
    });

    if (fixCount > 0) {
        fixes.push(`Converted ${fixCount} right:/bottom: positioning(s) to left:/top: with explicit pixel values (1920×1080 canvas)`);
    }

    return fixed;
}

// ====================================================================
// PHASE 5.4: STRING SAFETY
// ====================================================================

/**
 * Problem 14: Degree symbol ° (U+00B0) breaks esbuild parser in JSX string content.
 *             Remove it — use plain decimal notation: "35.6892 N" not "35.6892° N".
 */
function fixStringSafety(code, fixes) {
    let fixed = code;

    // Remove degree symbol ° — esbuild chokes on it in JSX string literals
    if (fixed.includes('\u00B0')) {
        fixed = fixed.replace(/\u00B0/g, '');
        fixes.push('Removed degree symbol ° from strings (breaks esbuild parser — use plain decimal notation)');
    }

    // Remove other common non-ASCII chars that break esbuild in JSX string literals
    // Keep emojis intact (high codepoints) — only strip the common problematic ones
    // · (U+00B7 middle dot) is safe — keep it
    // ° (U+00B0 degree) — already handled above

    return fixed;
}

// ====================================================================
// PHASE 5.5: WHITESPACE & OVERFLOW
// ====================================================================

/**
 * Problem 12: Text elements need whiteSpace: 'nowrap' to prevent unexpected text wrapping.
 *             Container elements with explicit dimensions need overflow: 'hidden' and
 *             boxSizing: 'border-box' to prevent content bleed.
 */
function fixWhitespaceOverflow(code, fixes) {
    let fixed = code;
    let textFixes = 0;
    let containerFixes = 0;

    // Add whiteSpace: 'nowrap' to div elements that have fontSize (text elements)
    fixed = safeStyleReplace(fixed, 'div', (styles) => {
        if (!styles.includes('fontSize')) return null;
        if (styles.includes('whiteSpace')) return null;
        textFixes++;
        const cleanStyles = styles.trimEnd().replace(/,?\s*$/, '');
        return injectIntoStyles(cleanStyles, "whiteSpace: 'nowrap'");
    });

    // Add overflow: 'hidden' + boxSizing: 'border-box' to positioned containers
    // with explicit width and height but missing overflow
    fixed = safeStyleReplace(fixed, 'div', (styles) => {
        // Must have explicit width AND height AND a position value
        if (!styles.includes('width') || !styles.includes('height')) return null;
        if (!styles.includes('position')) return null;
        if (styles.includes('overflow')) return null;

        const additions = ["overflow: 'hidden'"];
        if (!styles.includes('boxSizing')) additions.push("boxSizing: 'border-box'");

        containerFixes++;
        const cleanStyles = styles.trimEnd().replace(/,?\s*$/, '');
        return injectIntoStyles(cleanStyles, additions.join(', '));
    });

    if (textFixes > 0) {
        fixes.push(`Added whiteSpace: 'nowrap' to ${textFixes} text element(s) (prevents unexpected line breaks)`);
    }
    if (containerFixes > 0) {
        fixes.push(`Added overflow: 'hidden' + boxSizing: 'border-box' to ${containerFixes} positioned container(s)`);
    }

    return fixed;
}

// ====================================================================
// PHASE 5.6: SVG OVERLAY SANITIZER
// ====================================================================

/**
 * SVG-specific fixes for overlay layers in animated scenes.
 *
 * Common issues that cause black/blank screens in complex SVG scenes:
 *
 * 1. SVG overlay missing `overflow="visible"` — strokes at the SVG viewport boundary get
 *    clipped. Critical for strokeDashoffset animations where the arc may touch the edge.
 *
 * 2. SVG missing explicit HTML width/height attributes — without them, some browsers default
 *    the SVG viewport to 300×150, misaligning all coordinates vs. the CSS-sized element.
 *
 * 3. The `background: 'transparent'` on SVG is handled by Phase 5.1 → `backgroundColor`.
 *    Phase 5.6 doesn't need to repeat that, but it does guard against the CSS `overflow`
 *    property on SVG being set to 'hidden' (which clips animated strokes).
 */
function fixSVGOverlays(code, fixes) {
    let fixed = code;
    let fixCount = 0;

    // Fix 1: SVG overlays used as full-canvas layers need overflow="visible" so strokes
    // near the SVG viewport edge aren't clipped by the browser.
    // Only targets <svg> elements that have position:'absolute' in their style (overlay pattern).
    fixed = fixed.replace(
        /(<svg\b)([^>]*)(style=\{\{[^}]*position:\s*['"]absolute['"][^}]*\}\})([^>]*>)/g,
        (match, svgTag, before, styleAttr, after) => {
            // Already has overflow="visible" HTML attribute?
            if (/\boverflow\s*=\s*["']visible["']/.test(match)) return match;
            // Already has overflow:'visible' inside the style?
            if (/overflow:\s*['"]visible['"]/.test(styleAttr)) return match;
            fixCount++;
            return `${svgTag}${before} overflow="visible" ${styleAttr}${after}`;
        }
    );

    // Fix 2: If a CSS overflow:'hidden' is present on an SVG overlay, replace with 'visible'
    // so animated stroke paths near the edge are not clipped.
    fixed = safeStyleReplace(fixed, 'svg', (styles) => {
        if (!styles.includes("overflow: 'hidden'") && !styles.includes('overflow: "hidden"')) return null;
        if (!styles.includes('position')) return null;  // Only for positioned SVG overlays
        fixCount++;
        return styles
            .replace(/overflow:\s*'hidden'/g, "overflow: 'visible'")
            .replace(/overflow:\s*"hidden"/g, 'overflow: "visible"');
    });

    if (fixCount > 0) {
        fixes.push(`Fixed ${fixCount} SVG overlay issue(s) — set overflow="visible" to prevent stroke clipping on animated arcs`);
    }

    return fixed;
}


// ====================================================================
// PHASE 8.1: ROOT OVERFLOW GUARD
// ====================================================================
// The 1920×1080 root container MUST clip content with overflow:'hidden'.
// Without it, absolutely-positioned elements that animate from off-screen
// remain visible during the entire scene, producing streaks and artifacts.

function enforceRootOverflowHidden(code, fixes) {
    let fixed = code;

    // Find the first AbsoluteFill or the root div with width:1920
    const rootPatterns = [
        // AbsoluteFill style={{ ... }}
        { tag: 'AbsoluteFill', re: /(<AbsoluteFill\s+style=\{\{)([\s\S]*?)(\}\})/ },
        // Root div style={{ position:'absolute', top:0, left:0, width:1920, height:1080 ... }}
        { tag: 'div', re: /(<div\s+style=\{\{)([^}]*width:\s*1920[^}]*)(\}\})/ },
    ];

    for (const { re } of rootPatterns) {
        if (re.test(fixed)) {
            fixed = fixed.replace(re, (match, open, styles, close) => {
                if (/overflow:\s*['"]hidden['"]/.test(styles)) return match;
                fixes.push('Added overflow:hidden to root container (prevents out-of-frame artifacts)');
                return `${open}${styles}, overflow: 'hidden'${close}`;
            });
            break;
        }
    }

    return fixed;
}

// ====================================================================
// PHASE 8.2: FONT SIZE CLAMP
// ====================================================================
// Remotion renders at exactly 1920×1080 — font sizes below 12px are
// invisible and above 144px almost always overflow their containers.

function clampFontSizes(code, fixes, warnings) {
    let fixed = code;
    let clamped = 0;

    fixed = fixed.replace(/fontSize:\s*(\d+)/g, (match, size) => {
        const px = parseInt(size);
        if (px > 144) {
            clamped++;
            return `fontSize: 144`;
        }
        // Below 12px is already handled by fixTypography (bumps to 24px),
        // but catch anything that slipped through
        if (px > 0 && px < 12) {
            clamped++;
            return `fontSize: 18`;
        }
        return match;
    });

    if (clamped > 0) fixes.push(`Clamped ${clamped} font size(s) to 12–144px safe range`);
    return fixed;
}

// ====================================================================
// PHASE 8.3: TEXT CONTAINER WIDTH GUARD
// ====================================================================
// Text nodes that have no width or maxWidth can overflow the canvas
// when placeholder values are replaced with longer strings at fill time.

function guardTextContainerWidths(code, fixes, warnings) {
    let fixed = code;

    // Count text elements without explicit width/maxWidth
    const textTags = ['<Typography', '<p ', '<span ', '<h1 ', '<h2 ', '<h3 ', '<h4 '];
    let unconstrained = 0;

    for (const tag of textTags) {
        // Find style blocks on these tags and check for width/maxWidth
        const re = new RegExp(`${tag.replace('<', '<').replace(' ', '\\s+')}[^>]*style=\\{\\{([^}]*)\\}\\}`, 'g');
        for (const m of fixed.matchAll(re)) {
            const styles = m[1];
            if (!styles.includes('width') && !styles.includes('maxWidth')) {
                unconstrained++;
            }
        }
    }

    if (unconstrained > 3) {
        warnings.push(
            `${unconstrained} text element(s) have no width/maxWidth — long placeholder values may overflow. ` +
            `Add maxWidth or overflow:'hidden' to each text container.`
        );
    }

    return fixed;
}

// ====================================================================
// PHASE 8.4: CSS ANIMATION REMOVAL
// ====================================================================
// CSS animation: and transition: are ignored by Remotion's renderer.
// They cause elements to appear frozen (at frame 0 of the CSS keyframe)
// or produce unexpected static states.

function removeCSSAnimations(code, fixes) {
    let fixed = code;
    let removed = 0;

    // animation: 'fadeIn 2s ease' or animation: `...`  or animation: "..."
    fixed = fixed.replace(/\banimation:\s*(['"`][^'"`]*['"`]|[\w-]+\s[\d.]+s[^,}]*)/g, () => {
        removed++;
        return '/* animation removed — use interpolate(frame,...) instead */';
    });

    // transition: 'all 0.3s ease'  — CSS transitions also don't work in renders
    fixed = fixed.replace(/\btransition:\s*(['"`][^'"`]*['"`])/g, () => {
        removed++;
        return '/* transition removed — use interpolate(frame,...) instead */';
    });

    // @keyframes blocks in JSX template literals or style strings
    fixed = fixed.replace(/@keyframes\s+\w+\s*\{[^}]*\}/g, () => {
        removed++;
        return '/* keyframes removed */';
    });

    if (removed > 0) {
        fixes.push(`Removed ${removed} CSS animation/transition property(ies) — use interpolate(frame,...) for Remotion`);
    }

    return fixed;
}

// ====================================================================
// PHASE 8.5: SAFE ZONE WARNINGS
// ====================================================================
// Content within 40px of any edge may be cut off on displays with
// overscan. We warn but don't auto-reposition (layout intent unknown).

function warnSafeZoneViolations(code, warnings) {
    const EDGE_THRESHOLD = 40;
    const violations = [];

    // Scan for top: N, left: N, right: N, bottom: N with small values
    const edgeRe = /\b(top|left|right|bottom):\s*(\d+)/g;
    for (const m of code.matchAll(edgeRe)) {
        const prop = m[1];
        const val = parseInt(m[2]);
        if (val < EDGE_THRESHOLD && val >= 0) {
            violations.push(`${prop}:${val}`);
        }
    }

    if (violations.length > 0) {
        const unique = [...new Set(violations)].slice(0, 5).join(', ');
        warnings.push(
            `Safe zone: ${violations.length} position(s) within ${EDGE_THRESHOLD}px of edge (${unique}...). ` +
            `Keep critical content ≥96px from edges for broadcast safe area.`
        );
    }

    return code; // warnings only — no mutation
}
